name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
   check-bats-version:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v3
           with:
              node-version: "18"
         - run: npm install
         - run: npm run build:docs
         - name: Upload artifact
           uses: actions/upload-pages-artifact@v2
           with:
              path: docs/.vitepress/dist
